services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=development
      - APP_ENV=local
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=username
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=audit
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - ./swagger.yaml:/usr/src/app/swagger.yaml
    command: npm run start:dev

  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=audit
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
