openapi: 3.0.0
paths:
  /health:
    get:
      operationId: HealthController_check
      parameters: []
      responses:
        '200':
          description: The Health Check is successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  info:
                    type: object
                    example: &a1
                      database: &a2
                        status: up
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  error:
                    type: object
                    example: {}
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  details:
                    type: object
                    example: *a1
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
        '503':
          description: The Health Check is not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  info:
                    type: object
                    example: *a1
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  error:
                    type: object
                    example:
                      redis: &a3
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
                    nullable: true
                  details:
                    type: object
                    example:
                      database: *a2
                      redis: *a3
                    additionalProperties:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                      additionalProperties: true
      tags:
        - health-check
  /api/1/audits/chart-reviews:
    post:
      description:
        Creates a new chart review audit with EHR provider and patient
        information
      operationId: ChartReviewController_createChartReview_api/1
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChartReviewAuditDto'
      responses:
        '201':
          description: Chart reviews created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChartReviewResponseDto'
        '400':
          description: Invalid input data provided
      summary: Create a new chart reviews
      tags: &a4
        - Chart Review
  /api/1/audits/chart-reviews/{id}:
    get:
      description: Retrieves a chart review audit including EHR data if available
      operationId: ChartReviewController_getChartReview_api/1
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Chart review audit retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChartReviewResponseDto'
        '404':
          description: Chart review audit not found
      summary: Get a chart review audit
      tags: *a4
    patch:
      description: Updates a chart review audit status and/or line item responses
      operationId: ChartReviewController_updateChartReview_api/1
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChartReviewDto'
      responses:
        '200':
          description: The chart review audit has been successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChartReviewResponseDto'
        '400':
          description: Invalid update data provided
        '404':
          description: Chart review audit not found
      summary: Update a chart review audit
      tags: *a4
  /api/1/audits/chart-reviews/compliance:
    get:
      description:
        Retrieves compliance rates and statistics for chart review audits,
        including total audits, compliant audits, compliance rate, completed
        audits and completion rate. Can be filtered by EHR provider.
      operationId: ChartReviewController_getCompliance_api/1
      parameters:
        - name: assignedTo
          required: false
          in: query
          description: Filter by assigned user ID
          schema:
            type: string
        - name: unit
          required: false
          in: query
          description: Filter by unit ID
          schema:
            type: string
      responses:
        '200':
          description: Compliance statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChartReviewComplianceDto'
      summary: Get chart review compliance rates
      tags: *a4
  /api/1/audits:
    get:
      description: Retrieves a list of all audits with basic information
      operationId: AuditV1Controller_getAudits_api/1
      parameters: []
      responses:
        '200':
          description: List of audits retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuditFindAllDto'
      summary: Get all audits
      tags: &a5
        - Audits
  /api/1/audits/compliance:
    get:
      description: Retrieves compliance rates for audits with optional filters
      operationId: AuditV1Controller_getCompliance_api/1
      parameters:
        - name: type
          required: false
          in: query
          description: Filter compliance rates by audit type
          schema:
            enum:
              - chart-review
              - practice-audit
              - safety-audit
            type: string
        - name: unitId
          required: false
          in: query
          description: Filter compliance rates by unit ID
          schema:
            example: 123e4567-e89b-12d3-a456-426614174000
            type: string
        - name: assignedTo
          required: false
          in: query
          description: Filter compliance rates by assigned user ID
          schema:
            example: user-123e4567-e89b-12d3-a456-426614174000
            type: string
        - name: startDate
          required: true
          in: query
          description: Start date for the compliance query
          schema:
            example: 2023-01-01
            type: string
        - name: endDate
          required: true
          in: query
          description: End date for the compliance query
          schema:
            example: 2023-12-31
            type: string
      responses:
        '200':
          description: ''
      summary: Get audit compliance rates
      tags: *a5
info:
  title: API Documentation
  description: API description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    RecurrenceDto:
      type: object
      properties:
        frequency:
          type: string
          enum:
            - daily
            - weekly
            - monthly
            - quarterly
            - yearly
          description: Frequency of recurrence. Optional if audit is not recurring.
        interval:
          type: number
          description: Interval of recurrence (e.g., every 2 weeks)
          minimum: 1
        endDate:
          format: date-time
          type: string
          description: Optional end date for recurrence
      required:
        - interval
    CreateChartReviewAuditDto:
      type: object
      properties:
        assignedTo:
          type: string
          description:
            User ID the chart review is assigned to. Required if no unitId
            provided
        unitId:
          type: string
          description:
            Unit ID to assign the chart review to. Required if no assignedTo
            provided
        dueDate:
          format: date-time
          type: string
          description: Due date for the chart review
        ehrProvider:
          type: string
          description: ID of the EHR provider for the chart review
        patientId:
          type: string
          description: ID of the patient whose chart is being reviewed
        recurrence:
          description: Recurrence pattern for the chart review
          allOf:
            - $ref: '#/components/schemas/RecurrenceDto'
      required:
        - dueDate
        - ehrProvider
        - patientId
    ChartReviewResponseDto:
      type: object
      properties:
        id:
          type: string
        assignedTo:
          type: string
        dueDate:
          format: date-time
          type: string
        ehrProvider:
          type: string
        patientId:
          type: string
        status:
          type: string
        ehrData:
          type: object
        lineItems:
          type: array
          items:
            type: string
      required:
        - id
        - assignedTo
        - dueDate
        - ehrProvider
        - patientId
        - status
        - lineItems
    UpdateLineItemDto:
      type: object
      properties: {}
    UpdateChartReviewDto:
      type: object
      properties:
        status:
          type: string
          enum:
            - pending
            - in-progress
            - completed
          description: Updated status of the chart review audit
        lineItems:
          description: Updated responses for line items
          type: array
          items:
            $ref: '#/components/schemas/UpdateLineItemDto'
    ChartReviewComplianceDto:
      type: object
      properties:
        totalAudits:
          type: number
          description: Total number of audits
        compliantAudits:
          type: number
          description: Number of compliant audits
        complianceRate:
          type: number
          description: Compliance rate as a percentage
          minimum: 0
          maximum: 100
        completedAudits:
          type: number
          description: Number of completed audits
        completionRate:
          type: number
          description: Completion rate as a percentage
          minimum: 0
          maximum: 100
      required:
        - totalAudits
        - compliantAudits
        - complianceRate
        - completedAudits
        - completionRate
    AuditFindAllDto:
      type: object
      properties:
        id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
          description: Unique identifier of the audit
        assignedTo:
          type: string
          example: user-123e4567-e89b-12d3-a456-426614174000
          description: User ID the audit is assigned to
        dueDate:
          format: date-time
          type: string
          example: 2023-12-31T23:59:59Z
          description: Due date for the audit
        auditType:
          type: string
          enum:
            - chart-review
            - practice-audit
            - safety-audit
        status:
          type: string
          enum:
            - pending
            - in-progress
            - completed
      required:
        - id
        - assignedTo
        - dueDate
        - auditType
        - status
